//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUJ_DataTranfer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.201.1")]
        public string HostName {
            get {
                return ((string)(this["HostName"]));
            }
            set {
                this["HostName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("avi\\RGOZ-888")]
        public string PathInput {
            get {
                return ((string)(this["PathInput"]));
            }
            set {
                this["PathInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IntegrateDataToPLC")]
        public string SubFolderInput {
            get {
                return ((string)(this["SubFolderInput"]));
            }
            set {
                this["SubFolderInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TrayInput\\RGOZ-888")]
        public string PathOutput {
            get {
                return ((string)(this["PathOutput"]));
            }
            set {
                this["PathOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IntegrateData")]
        public string SubFolderOutput {
            get {
                return ((string)(this["SubFolderOutput"]));
            }
            set {
                this["SubFolderOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ByPassPartView {
            get {
                return ((bool)(this["ByPassPartView"]));
            }
            set {
                this["ByPassPartView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ByPassFileNameDelete {
            get {
                return ((bool)(this["ByPassFileNameDelete"]));
            }
            set {
                this["ByPassFileNameDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ByPassServer {
            get {
                return ((bool)(this["ByPassServer"]));
            }
            set {
                this["ByPassServer"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.1")]
        public string IpMachine
        {
            get
            {
                return ((string)(this["IPMachine"]));
            }
            set
            {
                this["IPMachine"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectShot1
        {
            get
            {
                return ((bool)(this["SelectShot1"]));
            }
            set
            {
                this["SelectShot1"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectShot2
        {
            get
            {
                return ((bool)(this["SelectShot2"]));
            }
            set
            {
                this["SelectShot2"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectShot3
        {
            get
            {
                return ((bool)(this["SelectShot3"]));
            }
            set
            {
                this["SelectShot3"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NOT_USE")]
        public string NumberPosition_Shot1
        {
            get
            {
                return ((string)(this["NumberPosition_Shot1"]));
            }
            set
            {
                this["NumberPosition_Shot1"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NOT_USE")]
        public string NumberPosition_Shot2
        {
            get
            {
                return ((string)(this["NumberPosition_Shot2"]));
            }
            set
            {
                this["NumberPosition_Shot2"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NOT_USE")]
        public string NumberPosition_Shot3
        {
            get
            {
                return ((string)(this["NumberPosition_Shot3"]));
            }
            set
            {
                this["NumberPosition_Shot3"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NOT_USE")]
        public string IndexData
        {
            get
            {
                return ((string)(this["IndexData"]));
            }
            set
            {
                this["IndexData"] = value;
            }
        }
    }
}
